### ISSUE TITLE
Image fails to start with Durable %SYS

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/zpm-dockerhub#33]
I'm building my image for Durable %SYS with Docker volumes:

```
FROM intersystemsdc/irishealth-community:2023.1.0.229.0-zpm
#FROM containers.intersystems.com/intersystems/irishealth-community:2023.1.0.229.0


USER root
RUN mkdir -p /iris/durable && chown ${ISC_PACKAGE_MGRUSER}:${ISC_PACKAGE_IRISGROUP} /iris/durable
USER ${ISC_PACKAGE_MGRUSER}
```

And start it like this:
```yaml
version: "2.2"
services:
  iris:
    user: "51773:51773"
    build: 
      context: .
      dockerfile: Dockerfile
    command: --check-caps false
    volumes:
      - iris-durable:/iris
    environment:
      - ISC_DATA_DIRECTORY=/iris/durable
volumes:
  iris-durable:
```

If I use the base image `containers.intersystems.com/intersystems/irishealth-community:2023.1.0.229.0` it works as expected, but if I use `intersystemsdc/irishealth-community:2023.1.0.229.0-zpm` it fails with:
```
iris  | [INFO] Executing command /docker-entrypoint.sh iris-after-start ...
iris  | [ERROR] /docker-entrypoint.sh: line 188: /usr/irissys/iris.init: Permission denied
iris  | [ERROR] Command "/docker-entrypoint.sh iris-after-start " exited with status 256
iris  | [FATAL] Error executing post-startup command
```
